export default {
  en: {
    youCanUseTheMultisignatureWallets: 'You can use the multisignature wallets',
    walletsAreSmartContractsWhichManageAssets: 'Wallets are smart contracts which manage assets and can be owned by multiple accounts. Unlike accounts, contract wallets are controlled by code, which means that it is possible to customize their behavior. The most common use-case are multi-signature wallets, that allow for transaction logging, withdrawal limits, and rule-sets for signatures required.',
    toUseStakeholders: 'To use stakeholders features such as Bonuses and Voting, you should deposit TIME tokens.',
    enterTheAmount: 'Enter the amount you wold like to deposit. You can require TIME once for testing purposes.',
    checkValueAndPress: 'Check value and press APPROVE to allow TIME holder contract to deposit your tokens. This is for your safety.',
    waitUntilAllowance: 'Wait until allowance will be updated and press LOCK. To withdraw enter the amount and press WITHDRAW.',
    howToMakeTime: 'How to make TIME token deposit?',
    depositTime: 'Deposit TIME',
    sendTokens: 'Send tokens',
    howToMakeATransfer: 'How to make a transfer?',
    ifYouPlanToMoveALargeAmountOfEther: 'If you plan to move a large amount of ether, you should test sending a small amount to your wallet first to ensure everything goes as planned.',
    enterTheAddressYouWouldLikeToSendTo: 'Enter the address you would like to send to in the “Recipient address” field.',
    enterTheAmountYouWouldLikeToSend: 'Enter the amount you would like to send.',
    checkValuesAndPressSend: 'Check values and press SEND.',
    ifYouWantToAllowAContract: 'If you want to allow a contract to send your tokens (not ETH) – repeat same but press APPROVE.',
  },
  ru: {
    youCanUseTheMultisignatureWallets: 'Вы можете использовать кошельки с мультиподписью',
    walletsAreSmartContractsWhichManageAssets: 'Кошельки это смартконтракты которые управляют ассетами и могут принадлежать нескольким аккаунтам. В отличие от аккаунтов, контракты кошельков управляются кодом, что означает возможность кастомизации их поведения. Наиболее распространенное использование это мультиподписные кошельки, которые позволяют выполнять логгирование транзакций, устанавливать лимиты выдачи, и наборы правил о необходимом количестве подписей.',
    toUseStakeholders: 'Для использование возможностей акционеров таких как Бонусы и Голосования, вы должны вложить TIME токены.',
    enterTheAmount: 'Введите сумму которую вы хотите вложить. Вы можете запросить TIME единожды в целях тестирования.',
    checkValueAndPress: 'Проверьте значение и нажмите ПОДТВЕРДИТЬ чтобы разрешить TIME holder контракту внести ваши токены. Это для вашей безопастности.',
    waitUntilAllowance: 'Подождите пока allowance не будет обновлено и нажмите LOCK. Для изъятия введите сумму и нажмите ИЗЪЯТЬ.',
    howToMakeTime: 'Как внести TIME токены?',
    depositTime: 'Внести TIME',
    sendTokens: 'Отправить токены',
    howToMakeATransfer: 'Как сделать перевод?',
    ifYouPlanToMoveALargeAmountOfEther: 'Если вы планируете переслать большую сумму эфира, вам сначала следует протестировать отправку малого количества на ваш кошелек чтобы убедится что все проходит как запланировано.',
    enterTheAddressYouWouldLikeToSendTo: 'Введите адрес на который вы хотите осуществить перевод в поле "Адрес получателя".',
    enterTheAmountYouWouldLikeToSend: 'Введите сумму кооторую вы хотели бы отправить.',
    checkValuesAndPressSend: 'Проверьте значения и нажмите ОТПРАВИТЬ.',
    ifYouWantToAllowAContract: 'Если вы хотите разрешить контракту отправлять ваши токены (не ETH) - повторите тоже самое, но нажмите ПОДТВЕРДИТЬ.',
  },
}

