/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const DUCK_LABOR_HOUR = 'laborHour'

export const LABOR_HOUR_WEB3_UPDATE = 'LABOR_HOUR/UPDATE'
export const LABOR_HOUR_UPDATE_WALLET = 'LABOR_HOUR/WALLET/CREATE'
export const LABOR_HOUR_UNSET_WALLET = 'LABOR_HOUR/WALLET/UNSET'
export const LABOR_HOUR_TX_CREATE = 'LABOR_HOUR/TX/CREATE'
export const LABOR_HOUR_TX_REMOVE = 'LABOR_HOUR/TX/REMOVE'
export const LABOR_HOUR_TX_UPDATE = 'LABOR_HOUR/TX/UPDATE'
export const LABOR_HOUR_DAOS_REGISTER = 'LABOR_HOUR/DAO/REGISTER'
export const LABOR_HOUR_SWAP_UPDATE = 'LABOR_HOUR/SWAP/UPDATE'
export const LABOR_HOUR_SWAP_LIST_UPDATE = 'LABOR_HOUR/SWAP/LIST/UPDATE'

export const LABOR_HOUR_TOKENS_UPDATE_LATEST_BLOCK = 'LABOR_HOUR/TOKEN/UPDATE_LATEST_BLOCK'
export const LABOR_HOUR_TOKENS_FETCHING = 'LABOR_HOUR/TOKEN/TOKENS_FETCHING'
export const LABOR_HOUR_TOKENS_FETCHED = 'LABOR_HOUR/TOKEN/TOKENS_FETCHED'
export const LABOR_HOUR_TOKENS_FAILED = 'LABOR_HOUR/TOKEN/TOKENS_FAILED'
export const LABOR_HOUR_DEPOSIT_PARAMS_UPDATE = 'LABOR_HOUR/DEPOSIT_PARAMS_UPDATE'
export const LABOR_HOUR_UPDATE_MINING_NODE_TYPE = 'LABOR_HOUR/MINING_NODE_TYPE/UPDATE'
export const LABOR_HOUR_UPDATE_DEPOSIT = 'LABOR_HOUR/DEPOSIT/UPDATE'
export const LABOR_HOUR_UPDATE_LOCKED_DEPOSIT = 'LABOR_HOUR/LOCKED_DEPOSIT/UPDATE'
export const LABOR_HOUR_UPDATE_FEE_MULTIPLIER = 'LABOR_HOUR/FEE_MULTIPLIER/UPDATE'
export const LABOR_HOUR_UPDATE_PROCESSING_STATUS = 'LABOR_HOUR/PROCESSING_STATUS/UPDATE'
export const LABOR_HOUR_UPDATE_TOTAL_REWARDS = 'LABOR_HOUR/TOTAL_REWARDS/UPDATE'
export const LABOR_HOUR_UPDATE_REWARDS_BLOCKS_LIST = 'LABOR_HOUR/REWARDS_BLOCKS_LIST/UPDATE'

// AtomicSwapERC20 events
export const EVENT_CLOSE = 'Close'
export const EVENT_EXPIRE = 'Expire'
export const EVENT_OPEN = 'Open'

// ChronoBankPlatformSidechain events
export const EVENT_REVOKE = 'Revoke'

export const CHRONOBANK_NODE_FEE_COEFFICIENT = 0.9

export const LABOR_HOUR_UPDATE_MIDDLEWARE_CONNECTING_STATUS = 'LABOR_HOUR/MIDDLEWARE_CONNECTING_STATUS/UPDATE'
export const STATUS_CONNECTED = 'connected'
export const STATUS_DISCONNECTED = 'disconnected'

