/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const DUCK_LABOR_HOUR = 'laborHour'

export const LABOR_HOUR_WEB3_UPDATE = 'LABOR_HOUR/UPDATE'
export const LABOR_HOUR_UPDATE_WALLET = 'LABOR_HOUR/WALLET/CREATE'
export const LABOR_HOUR_TX_CREATE = 'LABOR_HOUR/TX/CREATE'
export const LABOR_HOUR_TX_REMOVE = 'LABOR_HOUR/TX/REMOVE'
export const LABOR_HOUR_TX_UPDATE = 'LABOR_HOUR/TX/UPDATE'
export const LABOR_HOUR_DAOS_REGISTER = 'LABOR_HOUR/DAO/REGISTER'
export const LABOR_HOUR_SWAP_UPDATE = 'LABOR_HOUR/SWAP/UPDATE'

export const LABOR_HOUR_TOKENS_FETCHING = 'LABOR_HOUR/TOKEN/TOKENS_FETCHING'
export const LABOR_HOUR_TOKENS_FETCHED = 'LABOR_HOUR/TOKEN/TOKENS_FETCHED'
export const LABOR_HOUR_TOKENS_FAILED = 'LABOR_HOUR/TOKEN/TOKENS_FAILED'
export const LABOR_HOUR_DEPOSIT_PARAMS_UPDATE = 'LABOR_HOUR/DEPOSIT_PARAMS_UPDATE'

// AtomicSwapERC20 events
export const EVENT_CLOSE = 'Close'
export const EVENT_EXPIRE = 'Expire'
export const EVENT_OPEN = 'Open'

// ChronoBankPlatformSidechain events
export const EVENT_REVOKE = 'Revoke'
