export default {
  en: {
    reissue: 'Reissue',
    reissueAmount: 'Reissue amount',
    onCrowdsale: 'On crowdsale',
    issuedAmount: 'Issued amount',
    fee: 'fee',
    withoutFee: 'Without fee',
    managers: 'managers',
    revoke: 'Revoke',
    crowdsaleInfo: 'crowdsale info',
    send: 'Send to exchange',
    selectPlatform: 'Select a platform',
    selectToken: 'Select a token',
  },
  ru: {
    reissue: 'Переиздать',
    reissueAmount: 'Сумма переиздания',
    onCrowdsale: 'В фокусе',
    issuedAmount: 'Выданная сумма',
    fee: 'комиссия',
    withoutFee: 'без коммиссии',
    managers: 'менеджера(ов)',
    revoke: 'Отозвать',
    crowdsaleInfo: 'Информация о crowdsale',
    send: 'Обменять',
    selectPlatform: 'Выберите платформу',
    selectToken: 'Выберите токен',
  },
}
