export default {
  en: {
    dialogTitle: 'Add token',
    platformName: 'Platform',
    tokenSymbol: 'Token symbol',
    smallestUnit: 'Decimals places of smallest unit',
    reissuable: 'Reissuable',
    amount: 'Amount',
    withFee: 'With fee',
    feePercent: 'Fee percent',
    startWithCrowdsale: 'Start with crowdsale',
    description: 'Token full name',
    uploading: 'Uploading',
    choosePlatform: 'Choose platform',
    feeAddress: 'Fee address',
    addNewPlatform: 'Add new platform',
    platformError: 'Choose platform',
    PlatformNotSelected: 'Platform not selected',
  },
  ru: {
    dialogTitle: 'Добавить токен',
    platformName: 'Платформa',
    tokenSymbol: 'Символ токена',
    smallestUnit: 'Наименьшая единица',
    reissuable: 'Перевыпускаемый',
    amount: 'Сумма',
    withFee: 'С коммиссией',
    feePercent: 'Процент коммиссии',
    startWithCrowdsale: 'Начать с crowdsale',
    description: 'Название токена',
    uploading: 'Загрузка',
    choosePlatform: 'Выберите платформу',
    feeAddress: 'Адресс для коммиссии',
    addNewPlatform: 'Добавить новую платформу',
    platformError: 'Выберите платформу',
    PlatformNotSelected: 'Платформа не выбрана',
  },
}
