/**
 * Copyright 2017–2019, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 *
 * @flow
 */

export const DUCK_PROFILE = 'profile'

export const PROFILE_USER_PROFILE_FETCH = 'PROFILE/USER_PROFILE/FETCH'
export const PROFILE_USER_PROFILE_FETCH_SUCCESS = 'PROFILE/USER_PROFILE/FETCH_SUCCESS'
export const PROFILE_USER_PROFILE_FETCH_FAILURE = 'PROFILE/USER_PROFILE/FETCH_FAILURE'

export const PROFILE_USER_PROFILE_UPDATE = 'PROFILE/USER_PROFILE/UPDATE'
export const PROFILE_USER_PROFILE_UPDATE_SUCCESS = 'PROFILE/USER_PROFILE/UPDATE_SUCCESS'
export const PROFILE_USER_PROFILE_UPDATE_FAILURE = 'PROFILE/USER_PROFILE/UPDATE_FAILURE'

export const PROFILE_USER_INFO_FETCH = 'PROFILE/USER_INFO/FETCH'
export const PROFILE_USER_INFO_FETCH_SUCCESS = 'PROFILE/USER_INFO/FETCH_SUCCESS'
export const PROFILE_USER_INFO_FETCH_FAILURE = 'PROFILE/USER_INFO/FETCH_FAILURE'

export const PROFILE_USER_AVATAR_UPLOAD = 'PROFILE/UPLOAD_AVATAR/UPLOAD'
export const PROFILE_USER_AVATAR_UPLOAD_SUCCESS = 'PROFILE/UPLOAD_AVATAR/UPLOAD_SUCCESS'
export const PROFILE_USER_AVATAR_UPLOAD_FAILURE = 'PROFILE/UPLOAD_AVATAR/UPLOAD_FAILURE'

export const PROFILE_USER_AVATAR_DOWNLOAD = 'PROFILE/DOWNLOAD_AVATAR/DOWNLOAD'
export const PROFILE_USER_AVATAR_DOWNLOAD_SUCCESS = 'PROFILE/DOWNLOAD_AVATAR/DOWNLOAD_SUCCESS'
export const PROFILE_USER_AVATAR_DOWNLOAD_FAILURE = 'PROFILE/DOWNLOAD_AVATAR/DOWNLOAD_FAILURE'
