export default {
  en: {
    chooseToken: 'Choose token',
    dialogTitle: 'Create an exchange',
    showAllAvailableTokens: 'Show all available tokens',
    hideAllAvailableTokens: 'Hide all available tokens',
    availableExchangeBalance: 'Available exchange balance:',
    setThePrices: 'Set the prices:',
    buyPrice: 'Buy price (ETH)',
    sellPrice: 'Sell price (ETH)',
    create: 'Create',
    enterTokenSymbol: 'Enter token symbol',
  },
  ru: {
    chooseToken: 'Выберите токен',
    showAllAvailableTokens: 'Показать все доступные токены',
    hideAllAvailableTokens: 'Скрыть все доступные токены',
    dialogTitle: 'Создать обменник',
    availableExchangeBalance: 'Доступный баланс:',
    setThePrices: 'Установите цены:',
    buyPrice: 'Цена покупки (ETH)',
    sellPrice: 'Цена продажи (ETH)',
    create: 'Создать',
    enterTokenSymbol: 'Введите символ токена',
  },
}
