export { default as PageBase } from './PageBase'
export { default as LoginPage } from './LoginPage/LoginPage'
export { default as NotFoundPage } from './NotFound/NotFound'
export { default as CreateAccountPage } from './CreateAccountPage/CreateAccountPage'
export { default as SelectWalletPage } from './SelectWalletPage/SelectWalletPage'
export { default as RecoverAccountPage } from './RecoverAccountPage/RecoverAccountPage'
export { default as ResetPasswordPage } from './ResetPasswordPage/ResetPasswordPage'
