/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const DUCK_WAVES = 'txWaves'

export const WAVES_TX_CREATE = 'WAVES/TX_CREATE'
export const WAVES_TX_RESET = 'WAVES/TX_RESET'
export const WAVES_TX_STATUS = 'WAVES/TX_STATUS'
export const WAVES_TX_UPDATE = 'WAVES/TX_UPDATE'

export const WAVES_ENGINE_RESET_ALL = 'WAVES/ENGINE_RESET_ALL'
export const WAVES_ENGINE_RESET_HTTP = 'WAVES/ENGINE_RESET_HTTP'
export const WAVES_ENGINE_RESET_WS = 'WAVES/ENGINE_RESET_WS'

export const WAVES_ENGINE_HTTP_RECONNECT = 'WAVES/ENGINE_HTTP_RECONNECT'
export const WAVES_ENGINE_HTTP_RECONNECT_SUCCESS = 'WAVES/ENGINE_HTTP_RECONNECT_SUCCESS'
export const WAVES_ENGINE_HTTP_RECONNECT_FAILURE = 'WAVES/ENGINE_HTTP_RECONNECT_FAILURE'

export const WAVES_ENGINE_WS_RECONNECT = 'WAVES/ENGINE_WS_RECONNECT'
export const WAVES_ENGINE_WS_RECONNECT_SUCCESS = 'WAVES/ENGINE_WS_RECONNECT_SUCCESS'
export const WAVES_ENGINE_WS_RECONNECT_FAILURE = 'WAVES/ENGINE_WS_RECONNECT_FAILURE'

export const WAVES_PREPARE_NEW_TRANSACTION = 'WAVES/PREPARE_NEW_TRANSACTION'
export const WAVES_PREPARE_NEW_TRANSACTION_SUCCESS = 'WAVES/PREPARE_NEW_TRANSACTION_SUCCESS'
export const WAVES_PREPARE_NEW_TRANSACTION_FAILURE = 'WAVES/PREPARE_NEW_TRANSACTION_FAILURE'

export const WAVES_UPDATE_NEW_TRANSACTION = 'WAVES/UPDATE_NEW_TRANSACTION'
export const WAVES_UPDATE_NEW_TRANSACTION_SUCCESS = 'WAVES/UPDATE_NEW_TRANSACTION_SUCCESS'
export const WAVES_UPDATE_NEW_TRANSACTION_FAILURE = 'WAVES/UPDATE_NEW_TRANSACTION_FAILURE'

export const WAVES_SIGN_NEW_TRANSACTION = 'WAVES/SIGN_NEW_TRANSACTION'
export const WAVES_SIGN_NEW_TRANSACTION_SUCCESS = 'WAVES/SIGN_NEW_TRANSACTION_SUCCESS'
export const WAVES_SIGN_NEW_TRANSACTION_FAILURE = 'WAVES/SIGN_NEW_TRANSACTION_FAILURE'

export const WAVES_SEND_NEW_TRANSACTION = 'WAVES/SEND_NEW_TRANSACTION'
export const WAVES_SEND_NEW_TRANSACTION_SUCCESS = 'WAVES/SEND_NEW_TRANSACTION_SUCCESS'
export const WAVES_SEND_NEW_TRANSACTION_FAILURE = 'WAVES/SEND_NEW_TRANSACTION_FAILURE'

export const WAVES_SUBSCRIBE_ON_TOKEN = 'WAVES/SUBSCRIBE_ON_TOKEN'
export const WAVES_SUBSCRIBE_ON_TOKEN_SUCCESS = 'WAVES/SUBSCRIBE_ON_TOKEN_SUCCESS'
export const WAVES_SUBSCRIBE_ON_TOKEN_FAILURE = 'WAVES/SUBSCRIBE_ON_TOKEN_FAILURE'

export const WEB_SOCKET_CONNECTED = 'WEB_SOCKET/CONNECTED'
export const WEB_SOCKET_DISCONNECTED = 'WEB_SOCKET/DISCONNETED'
export const WEB_SOCKET_HEARTBEAT = 'WEB_SOCKET/HEARTBEAT'
export const WEB_SOCKET_ERROR = 'WEB_SOCKET/ERROR'
