export default {
  en: {
    orderBook: 'Order Book',
    traderAddress: 'Trader address',
    tradeLimits: 'Trade limits',
    price: 'Price',
    limits: 'Limits',
    buy: 'Buy',
    sell: 'Sell',
    tokens: 'tokens',
    sendRequest: 'send request',
    amountIn: 'Amount in',
    allowance: 'Your allowance',
    approve: 'Approve tokens',
    revoke: 'Revoke tokens',
    amountMustBeLess: 'Amount must be less than %{amount}',
  },
  ru: {
    orderBook: 'Книга Ордеров',
    traderAddress: 'Адрес трейдера',
    tradeLimits: 'Лимиты трейдера',
    price: 'Цена',
    limits: 'Лимиты',
    buy: 'Купить',
    sell: 'Продать',
    tokens: 'токены',
    sendRequest: 'отправить запрос',
    amountIn: 'Сумма в',
    allowance: 'Подтвержденная сумма',
    approve: 'Подтвердить перевод токенов',
    revoke: 'Отменить перевод токенов',
    amountMustBeLess: 'Количество должно быть меньше чем %{amount}',
  },
}
