export default {
  en: {
    orderBook: 'Order Book',
    traderAddress: 'Trader address',
    tradeLimits: 'Trade limits',
    price: 'Price',
    limits: 'Limits',
    buy: 'Buy',
    sell: 'Sell',
    tokens: 'tokens',
    sendRequest: 'send request',
    amountIn: 'Amount in',
  },
  ru: {
    orderBook: 'Книга Ордеров',
    traderAddress: 'Адрес трейдера',
    tradeLimits: 'Лимиты трейдера',
    price: 'Цена',
    limits: 'Лимиты',
    buy: 'Купить',
    sell: 'Продать',
    tokens: 'токены',
    sendRequest: 'отправить запрос',
    amountIn: 'Сумма в',
  },
}
