export default {
  en: {
    exchange: 'Exchange',
    exchangeAddress: 'Exchange address',
    search: 'Search',
    token: 'Token',
    buy: 'Buy',
    sell: 'Sell',
    amount: 'Amount',
    createExchange: 'Create an exchange',
    middlewareDisconnected: 'The search is not available because Middleware is disconnected',
    emptyList: 'List is empty',
  },
  ru: {
    exchange: 'Обмен',
    exchangeAddress: 'Адрес обменника',
    search: 'Поиск',
    token: 'Токен',
    buy: 'Купить',
    sell: 'Продать',
    amount: 'Сумма',
    createExchange: 'Создать обменник',
    middlewareDisconnected: 'Поиск недоступен, так как Middleware отключен',
    emptyList: 'Список пуст',
  },
}
