export default {
  en: {
    orderBook: 'Order Book',
    exchangeAddress: 'Exchange address',
    price: 'Price',
    buyPrice: 'Buy price',
    sellPrice: 'Sell price',
    buyLimits: 'Buy limits',
    sellLimits: 'Sell limits',
    limits: 'Limits',
    buy: 'Buy',
    sell: 'Sell',
    statusPending: 'Status: pending',
  },
  ru: {
    orderBook: 'Книга Ордеров',
    exchangeAddress: 'Адрес обменника',
    price: 'Цена',
    buyPrice: 'Цена продажи',
    sellPrice: 'Цена покупки',
    buyLimits: 'Лимит продажи',
    sellLimits: 'Лимит покупки',
    limits: 'Лимиты',
    buy: 'Купить',
    sell: 'Продать',
    statusPending: 'Статус: ожидает манинга',
  },
}
