/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const DUCK_LABOR_X_SIDECHAIN = 'laborXSidechain'
export const BLOCKCHAIN_LABOR_X_SIDECHAIN = 'LABOR_X_SIDECHAIN'
export const EOS = 'EOS'

export const LABOR_X_SIDECHAIN_WEB3_UPDATE = 'LABOR_X_SIDECHAIN/UPDATE'
export const LABOR_X_SIDECHAIN_UPDATE_WALLET = 'LABOR_X_SIDECHAIN/WALLET/CREATE'
export const LABOR_X_SIDECHAIN_TX_CREATE = 'LABOR_X_SIDECHAIN/TX/CREATE'
export const LABOR_X_SIDECHAIN_TX_REMOVE = 'LABOR_X_SIDECHAIN/TX/REMOVE'
export const LABOR_X_SIDECHAIN_TX_UPDATE = 'LABOR_X_SIDECHAIN/TX/UPDATE'
export const LABOR_X_SIDECHAIN_DAOS_REGISTER = 'LABOR_X_SIDECHAIN/DAO/REGISTER'
export const LABOR_X_SIDECHAIN_SWAP_UPDATE = 'LABOR_X_SIDECHAIN/SWAP/UPDATE'

export const LABOR_X_SIDECHAIN_TOKENS_FETCHING = 'LABOR_X_SIDECHAIN/TOKEN/TOKENS_FETCHING'
export const LABOR_X_SIDECHAIN_TOKENS_FETCHED = 'LABOR_X_SIDECHAIN/TOKEN/TOKENS_FETCHED'
export const LABOR_X_SIDECHAIN_TOKENS_FAILED = 'LABOR_X_SIDECHAIN/TOKEN/TOKENS_FAILED'

// AtomicSwapERC20 events
export const EVENT_CLOSE = 'Close'
export const EVENT_EXPIRE = 'Expire'
export const EVENT_OPEN = 'Open'

// ChronoBankPlatformSidechain events
export const EVENT_REVOKE = 'Revoke'

