export const prefix = 'WalletSelectDialog'

export default {
  en: {
    headerTitle: 'Choose Multisignature Wallet',
    headerSubtitle: 'Choose, Modify or Create Multisignature Wallets',
    addWallet: 'Add wallet',
    yourWallets: 'Your wallets',
    youHaveNoWallets: 'You have no wallets',
    numOwners: '%{num} owners',
    activeWallets: 'Active Wallets',
    timeLockedWallets: 'Time-locked Wallets',
    pending: 'Pending...',
    pendings: 'Pendings',
    requiredSignatures: 'Signatures req.',
    availableFunds: 'Available funds',
    unlockDate: 'Unlock Date',
    owners_1: 'Owner',
    owners_2: 'Owners',
    selectWallet: 'Select Wallet',
  },
  ru: {
    headerTitle: 'Выберите мультподписываемый кошелек',
    headerSubtitle: 'Choose, Modify or Create Multisignature Wallets',
    addWallet: 'Добавить кошелёк',
    yourWallets: 'Ваши кошельки',
    youHaveNoWallets: 'У вас нет кошельков',
    numOwners: '%{num} владельцев',
    activeWallets: 'Active Wallets',
    timeLockedWallets: 'Time-locked Wallets',
    pending: 'Pending...',
    pendings: 'Pendings',
    requiredSignatures: 'Signatures req.',
    availableFunds: 'Available funds',
    unlockDate: 'Unlock Date',
    owners_1: 'Владелец',
    owners_2: 'Владельца',
    owners_5: 'Владельцев',
    selectWallet: 'Select Wallet',
  },
}
