/* eslint-disable */
import optionalRequireFactory from 'optional-require'
const optionalRequire = optionalRequireFactory(require)

export const ChronoBankPlatformABI = optionalRequire('ChronoBankPlatform.json', true)
export const MultiEventsHistoryABI = optionalRequire('MultiEventsHistory.json', true)
export const WalletABI = optionalRequire('Wallet.json', true)
export const ContractsManagerABI = optionalRequire('ContractsManager.json', true)
export const ERC20ManagerABI = optionalRequire('ERC20Manager.json', true)
export const ExchangeABI = optionalRequire('Exchange.json', true)
export const FakeCoinABI = optionalRequire('FakeCoin.json', true)
export const FeeInterfaceABI = optionalRequire('FeeInterface.json', true)
export const ChronoBankAssetWithFeeProxyABI = optionalRequire('ChronoBankAssetWithFeeProxy.json', true)
export const LOCManagerABI = optionalRequire('LOCManager.json', true)
export const PendingManagerABI = optionalRequire('PendingManager.json', true)
export const PlatformsManagerABI = optionalRequire('PlatformsManager.json', true)
export const PlatformTokenExtensionGatewayManagerEmitterABI = optionalRequire('PlatformTokenExtensionGatewayManagerEmitter.json', true)
export const RewardsABI = optionalRequire('Rewards.json', true)
export const TimeHolderABI = optionalRequire('TimeHolder.json', true)
export const TokenManagementInterfaceABI = optionalRequire('TokenManagementInterface.json', true)
export const UserManagerABI = optionalRequire('UserManager.json', true)
export const VoteActorABI = optionalRequire('VoteActor.json', true)
export const PollManagerABI = optionalRequire('PollManager.json', true)
export const PollDetailsABI = optionalRequire('PollDetails.json', true)
export const WalletsManagerABI = optionalRequire('WalletsManager.json', true)
export const AssetDonatorABI = optionalRequire('AssetDonator.json', true)
export const ChronoBankAssetProxyABI = optionalRequire('ChronoBankAssetProxy.json', true)
export const AssetsManagerABI = optionalRequire('AssetsManager.json', true)
