/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const BITCOIN_TX_REJECT = 'BITCOIN/TX/REJECT'

// Overall Tx execute
export const BITCOIN_EXECUTE_TX = 'BITCOIN/EXECUTE/TX'
export const BITCOIN_EXECUTE_TX_SUCCESS = 'BITCOIN/EXECUTE/TX_SUCCESS'
export const BITCOIN_EXECUTE_TX_FAILURE = 'BITCOIN/EXECUTE/TX_FAILURE'

// Get UTXOS (exits) for bitcoin-like blockchain
export const BITCOIN_HTTP_GET_UTXOS = 'BITCOIN/HTTP/GET_UTXOS'
export const BITCOIN_HTTP_GET_UTXOS_SUCCESS = 'BITCOIN/HTTP/GET_UTXOS_SUCCESS'
export const BITCOIN_HTTP_GET_UTXOS_FAILURE = 'BITCOIN/HTTP/GET_UTXOS_FAILURE'
