/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

import {
  BLOCKCHAIN_BITCOIN,
  BLOCKCHAIN_DASH,
  BLOCKCHAIN_BITCOIN_CASH,
  BLOCKCHAIN_LITECOIN,
  BLOCKCHAIN_NEM,
  BLOCKCHAIN_WAVES,
} from '@chronobank/login/network/constants'

export const DUCK_BLOCKCHAINS = 'blockchains'

export const BLOCKCHAINS_LIST_UPDATE = 'blockchains/LIST_UPDATE'

export const DEFAULT_ACTIVE_WALLETS_LIST = [
  BLOCKCHAIN_BITCOIN,
  BLOCKCHAIN_BITCOIN_CASH,
  BLOCKCHAIN_LITECOIN,
  BLOCKCHAIN_DASH,
  BLOCKCHAIN_NEM,
  BLOCKCHAIN_WAVES,
]
