/**
 * Copyright 2017–2018, LaborX PTY
 * Licensed under the AGPL Version 3 license.
 */

export const DUCK_NODES = 'nodes'

export const NODES_INIT = 'NODES/INIT'
export const NODES_NETWORK_SWITCH = 'NODES/NETWORK/SWITCH'
export const NODES_NETWORK_SELECT = 'NODES/NETWORK/SELECT'
export const NODES_PRIMARY_NODE_ADD_CUSTOM_NODE = 'NODES/PRIMARY_NODE/ADD_CUSTOM_NODE'
export const NODES_PRIMARY_NODE_CONNECTED = 'NODES/PRIMARY_NODE/CONNECTED'
export const NODES_PRIMARY_NODE_DISABLE = 'NODES/PRIMARY_NODE/DISABLE'
export const NODES_PRIMARY_NODE_DISCONNECTED = 'NODES/PRIMARY_NODE/DISCONNECTED'
export const NODES_PRIMARY_NODE_ENABLE = 'NODES/PRIMARY_NODE/ENABLE'
export const NODES_PRIMARY_NODE_ERROR = 'NODES/PRIMARY_NODE/ERROR'
export const NODES_PRIMARY_NODE_GET_WEB3 = 'NODES/PRIMARY_NODE/GET_WEB3'
export const NODES_PRIMARY_NODE_GET_WEB3_PROVIDER = 'NODES/PRIMARY_NODE/WEB3_PROVIDER'
export const NODES_PRIMARY_NODE_RESUBSCRIBE_CONTRACTS = 'NODES/PRIMARY_NODE/RESUBSCRIBE_CONTRACTS'
export const NODES_PRIMARY_NODE_SWITCH = 'NODES/PRIMARY_NODE/SWITCH'
export const NODES_PRIMARY_NODE_SYNC_STATUS = 'NODES/PRIMARY_NODE/SYNC_STATUS'
export const NODES_PRIMARY_NODE_SYNC_STATUS_STOP = 'NODES/PRIMARY_NODE/SYNC_STATUS_STOP'
export const NODES_PRIMARY_NODE_SET_EXTERNAL_PROVIDER = 'NODES/PRIMARY_NODE/SET_EXTERNAL_PROVIDER'
